language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jbv1995/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jbv1995/react-test npm test -- --coverage

after_success:
  - docker build -t jbv1995/multi-client ./client
  - docker build -t jbv1995/multi-nginx ./nginx
  - docker build -t jbv1995/multi-server ./server
  - docker build -t jbv1995/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jbv1995/multi-client
  - docker push jbv1995/multi-nginx
  - docker push jbv1995/multi-server
  - docker push jbv1995/multi-worker